# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-21 22:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20180617_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfile',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductFile',
        ),
    ]
