# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-17 23:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180613_1551'),
        ('accounts', '0005_emailactivation'),
    ]

    operations = [
    ]
