# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-17 23:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_20180617_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cellphone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ci',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
    ]
