# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-21 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180617_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.NullBooleanField(),
        ),
    ]
