# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-27 00:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180621_1522'),
        ('accounts', '0009_auto_20180619_1944'),
    ]

    operations = [
    ]
