# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-27 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_merge_20180626_1757'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GuestEmail',
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
