# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-27 03:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20180626_1802'),
        ('accounts', '0010_merge_20180626_1704'),
    ]

    operations = [
    ]
